### ISSUE TITLE
[Feature Request] compact vs relaxed mode

### ISSUE THREAD

**Issue by shc023** [opticpower/tracker#15]
add a "compact" vs "relaxed" mode (next to the light/dark mode) that should have some theme implications.

1. needs compact vs relaxed theme files (base on geist-ui's theme spacing/font-size attributes)
2. needs to figure out how to merge them with the selected dark/light theme at the App level
3. needs to add `ThemeProvider` for` `styled-components`
4. needs to comb through all the inline styling and switch them to be `styled`
5. needs to comb through all the `styled` components and make it respect spacing/font-size attributes instead of hardcoded pixels

**Comment by a-villalobos** [comment]
@shc023 added it to pivotal
